Support lambdas and scoping functions in named arguments
facebook/ktfmt pull request #330
Opened 2022-06-22 19:37 UTC by nreid260

2022-07-22 21:23 UTC, davidtorosyan requested changes
The output looks good, but I have some comments on the implementation, nothing crazy though.

2022-07-22 21:23 UTC, davidtorosyan commented on core/src/test/java/com/facebook/ktfmt/format/FormatterTest.kt
> +  fun `named arguments indent scope functions block like`() =
Can you:
1. Add some tests with more than one parameters? Preceding, following, named, not-named, etc.
2. Add some Google format tests
3. Include a "before / after" example in the PR summary? Since this doesn't affect existing tests, it's harder to tell what it does. Unless it does affect existing tests and you haven't updated them yet :P

2022-07-22 21:23 UTC, davidtorosyan commented on core/src/main/java/com/facebook/ktfmt/format/KotlinInputAstVisitor.kt
> +    } finally {
This seems like a good change, but I'm not sure how it's useful. Are there cases in the formatter where we swallow exceptions? I'd imagine that if `block()` throws, the whole formatter goes out the window.

2022-07-22 21:23 UTC, davidtorosyan commented on core/src/main/java/com/facebook/ktfmt/format/KotlinInputAstVisitor.kt
> +  private fun visitLambdaOrScopingFunction(expr: KtExpression?) {
I know you didn't add this function, and this is actually an improvement, but the loose typing + an assertion error seems a little error prone. This probably isn't the place to address it, but good to revisit.

2022-07-22 21:23 UTC, davidtorosyan commented on core/src/main/java/com/facebook/ktfmt/format/KotlinInputAstVisitor.kt
> +    builder.guessToken("*") // In case of a spread argument
nit: if you check `isSpread` instead of guessing the token, the code comments itself :P

2022-07-22 21:23 UTC, davidtorosyan commented on core/src/main/java/com/facebook/ktfmt/format/KotlinInputAstVisitor.kt
> +          return
I'm not crazy about the early return, and if you can find a way to avoid it, that would be great.

I understand if that's not possible, but have you tried messing with the `isEnabled` parameter of `builder.block()`? Basically, I think all you need to do to accomplish what you're going for is disable the block IFF we're looking at a named lambda or scoping function.

Also, you might wanna rebase, because some of this code is changed in mainline.

2022-07-22 21:36 UTC, nreid260 commented on core/src/main/java/com/facebook/ktfmt/format/KotlinInputAstVisitor.kt
> +    builder.guessToken("*") // In case of a spread argument
`isSpread` is on `KtArgument` not `KtExpression`. I can't think of a better way to merge these two paths.

2022-07-22 21:39 UTC, nreid260 commented on core/src/main/java/com/facebook/ktfmt/format/KotlinInputAstVisitor.kt
> +    } finally {
It's not about exceptions, but control flow correctness. Because this is method is `inline`, calling `block()` can immediately return, skipping any subsequent statements. The fact that this is possible is a terrible language mistake.

2022-07-22 22:11 UTC, davidtorosyan commented on core/src/main/java/com/facebook/ktfmt/format/KotlinInputAstVisitor.kt
> +    } finally {
Yikes, I had no idea. Good catch.

I just looked it up though and I think adding crossinline to the lambda would help, because it would prevent non-local returns.

I'd be okay with either solution, this one is certainly more flexible. I'd recommend adding a comment about it though.

2022-07-22 22:30 UTC, nreid260 commented on core/src/main/java/com/facebook/ktfmt/format/KotlinInputAstVisitor.kt
> +    } finally {
The function could also not be `inline`. If nobody wants that control flow behaviour, there's no value in `inline` here.

2022-07-22 23:48 UTC, davidtorosyan commented on core/src/main/java/com/facebook/ktfmt/format/KotlinInputAstVisitor.kt
> +    } finally {
> there's no value in `inline` here.

There's potentially a perf benefit. I just tried removing the inline, and it increased format time by 1.4%. Not a huge amount (we're talking 3.40ms -> 3.45ms per file, or an increase of 50 microseconds per file), but hey, it's not nothing :)

> I do want that behaviour in the PR though...

I mentioned in another comment, but I think it's possible to not need the early return. Am I understanding right that the early return is to avoid entering the `block` and therefore the linebreaks/indentation that come with it? If so you can just use the `isEnabled` parameter. Let me know if I'm missing something.

2022-07-23 07:14 UTC, nreid260 commented
I want to continue this chain but I might pause until I can import 0.40 and rebase against that.

2023-09-15 14:45 UTC, hick209 commented
@nreid260, any status update on this PR?

2023-09-15 16:18 UTC, nreid260 commented
I do want to eventually merge something like this, but I suspect this one is stale. Basically I want ` = { ... }` in a named args to get the same treatment it would in an assignment, declaration, or expression function.

IIRC the main difficulty was arg around the spread operator `*` which doesn't apply to the currently supported cases and needs to be propagated for args.

I forget how lambdas are formatted in default params, but those should also be made consistent.

2023-09-15 16:22 UTC, hick209 commented
@nreid260, are you going to work on this in the near future? Else it might be work to close it and open a new one (or reopen this PR) when we're ready to tackle it

2023-09-15 16:27 UTC, closed without merging