Fix indentation of trailing comments in a bunch of cases
facebook/ktfmt pull request #418
Opened 2023-09-15 01:17 UTC by nreid260

2023-09-15 01:21 UTC, nreid260 commented
@hick209

2023-09-15 15:09 UTC, hick209 requested changes

2023-09-15 15:09 UTC, hick209 commented on core/src/main/java/com/facebook/ktfmt/format/KotlinInputAstVisitor.kt
> +      visitFunctionLikeExpression(
The function call here is missing the `contextReceiverList` param

2023-09-15 21:38 UTC, nreid260 commented
I discovered and fixed some other issues as well after the rebase.

2023-09-18 18:06 UTC, nreid260 commented
I noticed v.0.45 was just tagged. I was hoping to start using this soon. Any chance of quick v0.46 containing it?

2023-09-18 18:17 UTC, hick209 commented
Sure @nreid260, I can do another bump right after this lands

2023-09-18 18:40 UTC, closed without merging