WIP: Update ktfmt plugin for IntelliJ IDEA
facebook/ktfmt pull request #420
Opened 2023-09-18 21:40 UTC by greyhairredbear

Changes: 
- update build dependencies
 - gradle wrapper
 - intellij gradle plugin

2023-09-19 12:06 UTC, hick209 commented
I believe this will also fix #388

2023-09-24 00:47 UTC, greyhairredbear commented
Note for reviewers: The `google-java-format` plugin contains a test for `GoogleJavaFormatFormattingService`, which I haven't adjusted and ported for `ktfmt`. If required however, writing a similar test for `KtfmtFormattingService` should be possible.

2023-09-29 13:36 UTC, greyhairredbear commented
@cgrushko @strulovich Seems running the workflows on this PR need approval from a maintainer - would it be possible to run the workflows? 

Other than that, is there a way to get feedback on the changes? Could I help in any way?

2024-03-25 13:36 UTC, hick209 commented
Sorry the super long delay here @greyhairredbear. I went on paternity leave in September (son born on 22 of Sept) and once I was back early this year there were many things pilled up that took me a while to  go through.

I'm importing this internally for review and we should have some feedback for you this week.

2024-03-25 13:40 UTC, greyhairredbear commented
> Sorry the super long delay here @greyhairredbear. I went on paternity leave in September (son born on 22 of Sept) and once I was back early this year there were many things pilled up that took me a while to go through.
> 
> I'm importing this internally for review and we should have some feedback for you this week.

Hi, no need for excuses here. Congrats on your son, being a father of three, I completely understand the priorities here :) 

Happy about any feedback or change requests

2024-03-25 14:06 UTC, hick209 reviewed
I just have one question here, since I'm just mildly familiar with IJ API

2024-03-25 14:06 UTC, hick209 commented on ktfmt_idea_plugin/src/main/java/com/facebook/ktfmt/intellij/KtfmtFormattingService.java
> +            return true;
Any particular reason not to return a boolean flag here? We could set its value in the `run()` method

2024-03-26 19:42 UTC, hick209 requested changes
We are good to ship this internally, but I'm sending back to you to get an answer from the question I've asked above.

2024-03-27 14:12 UTC, greyhairredbear commented on ktfmt_idea_plugin/src/main/java/com/facebook/ktfmt/intellij/KtfmtFormattingService.java
> +            return true;
Sorry it took me so long to respond - I was quite busy at work and had to look that up. Unfortunately, `isRunUnderProgress` is a bit of an ambiguous name. 

I quote from the documentation: 
> Returns:
True if the task must be run under progress (a progress indicator is created automatically). Otherwise, the task is responsible for visualizing the progress by itself, it is just started on a background thread.

So the return value here is not about if the formatter is currently running, but rather if IntelliJ should handle showing a progress indicator to users.

2024-03-27 15:14 UTC, hick209 approved these changes

2024-03-27 15:44 UTC, closed without merging