Automatically manage trailing commas when running with --google-style
facebook/ktfmt pull request #427
Opened 2023-10-07 08:38 UTC by nreid260

Commas are added/removed according to the following rules:
  - Lambda param lists => remove
  - Single element lists => remove
  - Lists that fit on one line => remove
  - All other lists (multiline lists) => add

2023-10-07 08:40 UTC, nreid260 commented
@davidtorosyan @hick209 @cgrushko

I know we talked about this idea a bit several months ago. I've limited the impl to --google-style, but it could easily be expanded to more styles, or possibly a separate flag.

2023-11-07 00:07 UTC, nreid260 commented
@hick209 Is anyone available to review?

2023-11-07 20:05 UTC, hick209 commented
Hey @nreid260, sorry I'm out on paternity leave.

I'll ping the group internally to get into this though

2023-11-08 15:57 UTC, strulovich requested changes
Generally looks ok, and terribly sorry you had to wait for so long. A bunch of mostly style issues and requirement for extra documentation so it's easier to jump to and we should be good to go.

2023-11-08 15:57 UTC, strulovich commented on core/src/main/java/com/facebook/ktfmt/format/Formatter.kt
> +    return if (shebang.isNotEmpty()) { shebang + "\n" + formatted } else { formatted }
Style nit: If we're restyling this, maybe add this check to the let chain as well

2023-11-08 15:57 UTC, strulovich commented on core/src/main/java/com/facebook/ktfmt/format/FormattingOptions.kt
> +    val manageTrailingCommas: Boolean = false,
Could you please elaborate more? The best way would be with 1-2 code examples that explain what the user can expect to see.

2023-11-08 15:57 UTC, strulovich commented on core/src/main/java/com/facebook/ktfmt/format/RedundantElementManager.kt
> +        })
You can just use `forEachDescendantOfType` or `collectDescendantsOfType` for shorter and simpler code.

2023-11-08 15:57 UTC, strulovich commented on core/src/main/java/com/facebook/ktfmt/format/TrailingCommas.kt
> +        return // Only suggest trailing commas where there is already a line break
Again, a bunch of code examples above the method would really help people maintaining this years from now

2023-11-08 15:57 UTC, strulovich commented on core/src/main/java/com/facebook/ktfmt/format/TrailingCommas.kt
> +  private fun PsiElement.leftLeafIgnoringCommentsAndWhitespace(): PsiElement {
Add examples code and what it means

2023-11-08 15:57 UTC, strulovich commented on core/src/main/java/com/facebook/ktfmt/format/TrailingCommas.kt
> +    //  - destructuring declarations
This is not Meta style, so let's try to stick to something that's more applicable: Can you open issues and link to them from the TODO instead? You can have the issues assigned to you.

2023-11-08 20:45 UTC, nreid260 commented on core/src/main/java/com/facebook/ktfmt/format/RedundantElementManager.kt
> +        })
takeElement decides which elements to track. It would be error prone to duplicate that knowledge into the traversal.

2023-11-08 21:26 UTC, nreid260 commented on core/src/main/java/com/facebook/ktfmt/format/TrailingCommas.kt
> +        return // Only suggest trailing commas where there is already a line break
Done.

2023-11-08 22:10 UTC, nreid260 commented on core/src/main/java/com/facebook/ktfmt/format/TrailingCommas.kt
> +  private fun PsiElement.leftLeafIgnoringCommentsAndWhitespace(): PsiElement {
Done.

2023-11-08 22:10 UTC, nreid260 commented on core/src/main/java/com/facebook/ktfmt/format/FormattingOptions.kt
> +    val manageTrailingCommas: Boolean = false,
Done.

2023-11-08 22:10 UTC, nreid260 commented on core/src/main/java/com/facebook/ktfmt/format/Formatter.kt
> +    return if (shebang.isNotEmpty()) { shebang + "\n" + formatted } else { formatted }
Done.

2023-11-09 18:32 UTC, davidtorosyan commented on core/src/main/java/com/facebook/ktfmt/format/RedundantElementManager.kt
> +    // TODO(nickreid): Generalize this for addtional sugested elements.
Same comment here re: TODOs

2023-11-09 18:32 UTC, davidtorosyan commented on core/src/main/java/com/facebook/ktfmt/format/Formatter.kt
> +      .let { if (shebang.isEmpty()) it else shebang + "\n" + it }
love it

2023-11-09 19:35 UTC, nreid260 commented on core/src/main/java/com/facebook/ktfmt/format/RedundantElementManager.kt
> +    // TODO(nickreid): Generalize this for addtional sugested elements.
Done.

2023-11-11 01:45 UTC, strulovich reviewed
LGTM

2023-11-11 01:45 UTC, strulovich commented on core/src/main/java/com/facebook/ktfmt/format/RedundantElementManager.kt
> +        })
I don't think I understood your comment, I was suggesting:
```
file.forEachDescendantOfType<KtElement> {
  trailingommaSuggestor.takeElement(element)
}
```

2023-11-11 06:04 UTC, nreid260 commented
Ooooh, yeah that seems fine.

2023-11-11 06:25 UTC, closed without merging