Support disabling ordering doc tags in command line
facebook/ktfmt pull request #474
Opened 2024-06-05 12:05 UTC by omarismail94

Tested: Added unit test

Also compiled the JAR and tested it running
 java -jar /Users/omarismail/Desktop/ktfmt/core/target/ktfmt-0.50-SNAPSHOT-jar-with-dependencies.jar --kotlinlang-style --do-not-order-doc-tags compose/runtime/runtime-saveable/src/commonMain/kotlin/androidx/compose/runtime/saveable/RememberSaveable.kt

and it did not re-order the kdcoc tags in the kotlin file, as expected

Fixed: Issue #406

2024-06-05 12:09 UTC, omarismail94 commented
Signed CLA

2024-06-05 12:28 UTC, hick209 approved these changes

2024-06-05 12:57 UTC, omarismail94 commented on core/src/main/java/com/facebook/ktfmt/kdoc/KDocFormattingOptions.kt
> +    var orderDocTags: Boolean = true
Done, thanks!

2024-06-05 13:28 UTC, hick209 approved these changes

2024-06-05 13:42 UTC, hick209 approved these changes

2024-06-05 16:06 UTC, hick209 requested changes
I'm actually not sure we want this option to be exposed as a CLI param.
I'm discussing it internally at first, but wanted to give you a heads up

2024-06-05 17:55 UTC, hick209 commented
I understand why the feature is needed, but not why you need direct CLI exposure yet.
A workaround for it would be to build a simple Java program and runs ktfmt for you, where you set it up appropriately, if you don't want to touch the Google style

2024-06-05 22:38 UTC, omarismail94 commented
> I understand why the feature is needed, but not why you need direct CLI exposure yet. A workaround for it would be to build a simple Java program and runs ktfmt for you, where you set it up appropriately, if you don't want to touch the Google style

Ah OK, so I can keep the feature exposed in FormattingOptions, but not via CLI? 

I wanted to expose in CLI as that way, if I were to package the JAR as in intellij plugin, I can give it the flag to not re-order the tags. This would be a nice to have.

2024-06-06 10:17 UTC, omarismail94 commented
I changed it so `orderDocTags` is only in FormattingOptions and not avaialble via CLI

2024-06-06 16:10 UTC, omarismail94 commented
Im going to close this in preference for PR #475

2024-06-06 16:10 UTC, closed without merging