Add CLI --help option
facebook/ktfmt pull request #477
Opened 2024-06-10 19:54 UTC by grodin

Intended to land on top of #476

2024-06-11 01:07 UTC, hick209 reviewed
I like the direction and honestly this could happen before we land the `--style` change as adding an option does not break the API.

Your call though

2024-06-11 01:07 UTC, hick209 commented on core/src/main/java/com/facebook/ktfmt/cli/ParsedArgs.kt
> +      |  --style=kotlinlang                Kotlin language guidelines style
Thoughts?
```
--style=kotlinlang | google | dropbox   style for formatting approach
                                        kotlinlang - https://kotlinlang.org/docs/coding-conventions.html
                                        google     - add link
                                        dropbox    - Use 4-space block indenting
```

2024-06-11 01:07 UTC, hick209 commented on core/src/main/java/com/facebook/ktfmt/cli/Main.kt
> +          }
🫶

2024-06-11 01:07 UTC, hick209 commented on core/src/main/java/com/facebook/ktfmt/cli/ParsedArgs.kt
> +      if (args.contains("--help"))
```
"--help" in args || "-h" in args
```

2024-06-11 01:07 UTC, hick209 commented on core/src/main/java/com/facebook/ktfmt/cli/ParsedArgs.kt
> +      |passed, Facebook's style is used.
Let's put Meta here instead. I plan on making that an explicit style. That way we can state that it is the default
`s/Facebook/Meta/`

2024-06-11 10:53 UTC, grodin commented on core/src/main/java/com/facebook/ktfmt/cli/ParsedArgs.kt
> +      |  ktfmt @ARGFILE
Good catch, the `style=` change hasn't landed yet so this is incorrect anyway until then.

Some GNU tools (cp, mv, rsync) list their calling methods like this:

```
Usage: cp [OPTION] ...
  or:  cp [OPTION] ...
  or:  cp [OPTION] ...
```

and others (ripgrep, jq, bash) just list them similar to this:
```
Usage:
    rg [OPTIONS] ...
    rg [OPTIONS] ...
```

I think we should go for one or the other. I slightly prefer the second, ripgrep/jq style.

2024-06-11 10:57 UTC, grodin commented on core/src/main/java/com/facebook/ktfmt/cli/ParsedArgs.kt
> +      |  --style=kotlinlang                Kotlin language guidelines style
Again, this should have been the prior `--dropbox-style` etc. prior to the change.

I like your suggestion for when that lands though!

Reverted in 6dec31543cfb688627fdbe43600b5adc0709f055

2024-06-11 10:59 UTC, grodin commented on core/src/main/java/com/facebook/ktfmt/cli/ParsedArgs.kt
> +      |passed, Facebook's style is used.
69f879a7931c598ccc16382856406648f0927e5c

2024-06-11 11:02 UTC, grodin commented on core/src/main/java/com/facebook/ktfmt/cli/ParsedArgs.kt
> +      if (args.contains("--help"))
69f879a7931c598ccc16382856406648f0927e5c

2024-06-11 11:02 UTC, grodin commented on core/src/main/java/com/facebook/ktfmt/cli/ParsedArgs.kt
> +      |passed, Facebook's style is used.
2573612d4091d90dc4e030fdb0be2cb3a66d38fe

2024-06-11 12:18 UTC, hick209 requested changes

2024-06-11 12:18 UTC, hick209 commented on core/src/main/java/com/facebook/ktfmt/cli/ParsedArgs.kt
> +      |  ktfmt @ARGFILE
Good idea to follow what other well know CLI programs do.

Make sure to update the `style=` here and I can import this PR internally

2024-06-12 02:26 UTC, hick209 commented on core/src/main/java/com/facebook/ktfmt/cli/ParsedArgs.kt
> +      |  ktfmt @ARGFILE
Should we add something like "for more info use --help" in the general `USAGE` message? WDYT?

2024-06-12 11:57 UTC, hick209 commented on core/src/main/java/com/facebook/ktfmt/cli/Main.kt
> +            err.println(processArgs.message)
Why `err`? Shouldn't it be `out` here?

2024-06-12 12:04 UTC, grodin commented on core/src/main/java/com/facebook/ktfmt/cli/Main.kt
> +            err.println(processArgs.message)
Yep, you're right.

2024-06-12 12:06 UTC, hick209 commented on core/src/main/java/com/facebook/ktfmt/cli/ParsedArgs.kt
> +      |
```kotlin
    val HELP_TEXT = """
      |ktfmt - command line Kotlin source code pretty-printer
      |
```

2024-06-12 12:06 UTC, hick209 commented on core/src/main/java/com/facebook/ktfmt/cli/ParsedArgs.kt
> +      |     $ ktfmt --dropbox-style Main.kt src/Parser.kt
Need to update now that dropbox style is gone
```kotlin
      |     $ ktfmt --kotlinlang-style Main.kt src/Parser.kt
```

2024-06-12 12:06 UTC, hick209 commented on core/src/main/java/com/facebook/ktfmt/cli/ParsedArgs.kt
> +      |  --kotlinlang-style                Kotlin language guidelines style
1. Add `help` option
2. remove dropbox style
3. add meta style and mention it is the default
4. don't forget the `stdin-name` param

```kotlin
      |Commands options:
      |  -h, --help                        Show this help message
      |  -n, --dry-run                     Don't write to files, only report files which 
      |                                        would have changed
      |  --meta-style                      Use 2-space block indenting (default)
      |  --google-style                    Google internal style (2 spaces)
      |  --kotlinlang-style                Kotlin language guidelines style (4 spaces)
      |  --stdin-name=<name>               Name to report when formatting code from stdin
```

2024-06-12 17:46 UTC, hick209 commented
Which might be the last before 1.0.0

2024-06-13 15:21 UTC, hick209 approved these changes

2024-06-13 16:19 UTC, hick209 commented
Merging...

2024-06-13 16:28 UTC, closed without merging