Add test examples for non-ideal situations
facebook/ktfmt pull request #488
Opened 2024-06-19 01:35 UTC by snowe2010

2024-06-21 18:16 UTC, davidtorosyan requested changes
Thanks for adding more tests! I left some comments about moving them to the right places / adjusting the options. This is mainly to help with maintainability (the more tests have the same set of options, the easier to reason about).

2024-06-21 18:16 UTC, davidtorosyan commented on core/src/test/java/com/facebook/ktfmt/format/GoogleStyleFormatterKtTest.kt
> +    fun `Trailing comma forces variable value in list onto new line with manageTrailingCommas turned off`() =
Move to `FormatterTest.kt`, omit `FormattingOptions`

2024-06-21 18:16 UTC, davidtorosyan commented on core/src/test/java/com/facebook/ktfmt/format/GoogleStyleFormatterKtTest.kt
> +    fun `nested functions, maps, and statements in named parameters`() =
Move to `FormatterTest.kt`, omit `formattingOptions ` if possible

2024-06-21 18:16 UTC, davidtorosyan commented on core/src/test/java/com/facebook/ktfmt/format/GoogleStyleFormatterKtTest.kt
> +    fun `complex calls and calculation in named parameters with wrapping`() =
Move to `FormatterTest.kt`, omit `formattingOptions ` if possible

2024-06-21 18:16 UTC, davidtorosyan commented on core/src/test/java/com/facebook/ktfmt/format/GoogleStyleFormatterKtTest.kt
> +    fun `complex calls and calculation in named parameters without wrapping`() =
Move to `FormatterTest.kt`, omit `formattingOptions ` if possible

2024-06-21 18:16 UTC, davidtorosyan commented on core/src/test/java/com/facebook/ktfmt/format/GoogleStyleFormatterKtTest.kt
> +    fun `long call chains in named parameters`() =
Remove `formattingOptions`, this file automatically picks up google style

2024-06-27 17:12 UTC, snowe2010 commented on core/src/test/java/com/facebook/ktfmt/format/GoogleStyleFormatterKtTest.kt
> +    fun `Trailing comma forces variable value in list onto new line with manageTrailingCommas turned off`() =
Hm. but the test is showing the bug with the formatting options. If I omit that, the test will act differently. I've gone ahead and moved it to the FormatterTest, but left the FormattingOptions in, else the test is pointless.

2024-06-27 18:10 UTC, snowe2010 reviewed
@davidtorosyan I also added one more test around `if` expression functions

2024-06-27 18:10 UTC, snowe2010 commented on core/src/test/java/com/facebook/ktfmt/format/GoogleStyleFormatterKtTest.kt
> +    fun `long call chains in named parameters`() =
done.

2024-08-07 20:31 UTC, hick209 commented
We apologize for the delay. Let's try to get another look into this

2024-08-08 14:17 UTC, closed without merging