Convert IntelliJ plugin to Kotlin
facebook/ktfmt pull request #502
Opened 2024-08-07 18:48 UTC by rock3r

This PR is the basis for future improvements of the plugin. In this PR, the plugin code is converted to Kotlin, the configurable is recreated with the Kotlin UI DSL, and the goal is to maintain the existing behaviours.

The only small change is that the style dropdown in the configurable is disabled when ktfmt is disabled.

2024-08-07 21:09 UTC, hick209 requested changes
Overall this LGTM, but please mark the files as a move so we don't lose blame history.

2024-08-07 21:29 UTC, rock3r commented
Not sure how to do that? I didn't know you could override what diff thinks happened

2024-08-07 22:31 UTC, rock3r commented
@hick209 please advise so I can look into it tomorrow

2024-08-08 10:33 UTC, rock3r commented
@hick209 I tried looking into this but I did not find a way to force Git to consider files as moved. I had kept the actual conversion of the files to Kotlin to a dedicated commit, too, but that did not help. Also tried re-doing the conversion in another branch by committing the moving first, and the conversion second, but the conversion still results in pairs of adding/deleting

2024-08-08 10:41 UTC, hick209 commented
Yeah I looked it up as well and noticed this is not really doable in git :-/ 

I'm used to working with Mercurial, which allows this with the following command:
```
hg mv FROM TO --after
```

No worries, I can try to do that internally once we pull your changes. I have to wait until we merge the other 2 PRs for this though.

Thanks a ton for you contributions!

2024-08-08 12:30 UTC, hick209 commented on ktfmt_idea_plugin/build.gradle.kts
> +spotless { java { googleJavaFormat(libs.versions.googleJavaFormat.get()) } }
Now that we're on Kotlin, I guess we could even remove this

2024-08-08 12:33 UTC, rock3r commented on ktfmt_idea_plugin/build.gradle.kts
> +spotless { java { googleJavaFormat(libs.versions.googleJavaFormat.get()) } }
True, will do. Btw, I formatted the Kotlin code with ktfmt, using the Meta style IIRC. Is that the correct one?

2024-08-08 19:35 UTC, closed without merging